/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.jooq.tables.records;


import de.netbeacon.xenia.jooq.tables.Guilds;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record8<Long, LocalDateTime, String, Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guilds.guild_id</code>.
     */
    public GuildsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guilds.creation_timestamp</code>.
     */
    public GuildsRecord setCreationTimestamp(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.creation_timestamp</code>.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.guilds.preferred_language</code>.
     */
    public GuildsRecord setPreferredLanguage(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.preferred_language</code>.
     */
    public String getPreferredLanguage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.guilds.license_id</code>.
     */
    public GuildsRecord setLicenseId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.license_id</code>.
     */
    public Integer getLicenseId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.guilds.meta_guildname</code>.
     */
    public GuildsRecord setMetaGuildname(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.meta_guildname</code>.
     */
    public String getMetaGuildname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.guilds.meta_iconurl</code>.
     */
    public GuildsRecord setMetaIconurl(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.meta_iconurl</code>.
     */
    public String getMetaIconurl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.guilds.guild_prefix</code>.
     */
    public GuildsRecord setGuildPrefix(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.guild_prefix</code>.
     */
    public String getGuildPrefix() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.guilds.guild_settings</code>.
     */
    public GuildsRecord setGuildSettings(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.guild_settings</code>.
     */
    public Integer getGuildSettings() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, LocalDateTime, String, Integer, String, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, LocalDateTime, String, Integer, String, String, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Guilds.GUILDS.GUILD_ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Guilds.GUILDS.CREATION_TIMESTAMP;
    }

    @Override
    public Field<String> field3() {
        return Guilds.GUILDS.PREFERRED_LANGUAGE;
    }

    @Override
    public Field<Integer> field4() {
        return Guilds.GUILDS.LICENSE_ID;
    }

    @Override
    public Field<String> field5() {
        return Guilds.GUILDS.META_GUILDNAME;
    }

    @Override
    public Field<String> field6() {
        return Guilds.GUILDS.META_ICONURL;
    }

    @Override
    public Field<String> field7() {
        return Guilds.GUILDS.GUILD_PREFIX;
    }

    @Override
    public Field<Integer> field8() {
        return Guilds.GUILDS.GUILD_SETTINGS;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreationTimestamp();
    }

    @Override
    public String component3() {
        return getPreferredLanguage();
    }

    @Override
    public Integer component4() {
        return getLicenseId();
    }

    @Override
    public String component5() {
        return getMetaGuildname();
    }

    @Override
    public String component6() {
        return getMetaIconurl();
    }

    @Override
    public String component7() {
        return getGuildPrefix();
    }

    @Override
    public Integer component8() {
        return getGuildSettings();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreationTimestamp();
    }

    @Override
    public String value3() {
        return getPreferredLanguage();
    }

    @Override
    public Integer value4() {
        return getLicenseId();
    }

    @Override
    public String value5() {
        return getMetaGuildname();
    }

    @Override
    public String value6() {
        return getMetaIconurl();
    }

    @Override
    public String value7() {
        return getGuildPrefix();
    }

    @Override
    public Integer value8() {
        return getGuildSettings();
    }

    @Override
    public GuildsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildsRecord value2(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public GuildsRecord value3(String value) {
        setPreferredLanguage(value);
        return this;
    }

    @Override
    public GuildsRecord value4(Integer value) {
        setLicenseId(value);
        return this;
    }

    @Override
    public GuildsRecord value5(String value) {
        setMetaGuildname(value);
        return this;
    }

    @Override
    public GuildsRecord value6(String value) {
        setMetaIconurl(value);
        return this;
    }

    @Override
    public GuildsRecord value7(String value) {
        setGuildPrefix(value);
        return this;
    }

    @Override
    public GuildsRecord value8(Integer value) {
        setGuildSettings(value);
        return this;
    }

    @Override
    public GuildsRecord values(Long value1, LocalDateTime value2, String value3, Integer value4, String value5, String value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Long guildId, LocalDateTime creationTimestamp, String preferredLanguage, Integer licenseId, String metaGuildname, String metaIconurl, String guildPrefix, Integer guildSettings) {
        super(Guilds.GUILDS);

        setGuildId(guildId);
        setCreationTimestamp(creationTimestamp);
        setPreferredLanguage(preferredLanguage);
        setLicenseId(licenseId);
        setMetaGuildname(metaGuildname);
        setMetaIconurl(metaIconurl);
        setGuildPrefix(guildPrefix);
        setGuildSettings(guildSettings);
    }
}
