/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.jooq.tables.records;


import de.netbeacon.xenia.jooq.tables.Members;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembersRecord extends UpdatableRecordImpl<MembersRecord> implements Record7<Long, Long, LocalDateTime, String, Boolean, Boolean, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.members.guild_id</code>.
     */
    public MembersRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.members.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.members.user_id</code>.
     */
    public MembersRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.members.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.members.creation_timestamp</code>.
     */
    public MembersRecord setCreationTimestamp(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.members.creation_timestamp</code>.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.members.meta_nickname</code>.
     */
    public MembersRecord setMetaNickname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.members.meta_nickname</code>.
     */
    public String getMetaNickname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.members.meta_is_owner</code>.
     */
    public MembersRecord setMetaIsOwner(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.members.meta_is_owner</code>.
     */
    public Boolean getMetaIsOwner() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.members.meta_is_administrator</code>.
     */
    public MembersRecord setMetaIsAdministrator(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.members.meta_is_administrator</code>.
     */
    public Boolean getMetaIsAdministrator() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.members.level_points</code>.
     */
    public MembersRecord setLevelPoints(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.members.level_points</code>.
     */
    public Long getLevelPoints() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, LocalDateTime, String, Boolean, Boolean, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, LocalDateTime, String, Boolean, Boolean, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Members.MEMBERS.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return Members.MEMBERS.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Members.MEMBERS.CREATION_TIMESTAMP;
    }

    @Override
    public Field<String> field4() {
        return Members.MEMBERS.META_NICKNAME;
    }

    @Override
    public Field<Boolean> field5() {
        return Members.MEMBERS.META_IS_OWNER;
    }

    @Override
    public Field<Boolean> field6() {
        return Members.MEMBERS.META_IS_ADMINISTRATOR;
    }

    @Override
    public Field<Long> field7() {
        return Members.MEMBERS.LEVEL_POINTS;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationTimestamp();
    }

    @Override
    public String component4() {
        return getMetaNickname();
    }

    @Override
    public Boolean component5() {
        return getMetaIsOwner();
    }

    @Override
    public Boolean component6() {
        return getMetaIsAdministrator();
    }

    @Override
    public Long component7() {
        return getLevelPoints();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationTimestamp();
    }

    @Override
    public String value4() {
        return getMetaNickname();
    }

    @Override
    public Boolean value5() {
        return getMetaIsOwner();
    }

    @Override
    public Boolean value6() {
        return getMetaIsAdministrator();
    }

    @Override
    public Long value7() {
        return getLevelPoints();
    }

    @Override
    public MembersRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public MembersRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public MembersRecord value3(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public MembersRecord value4(String value) {
        setMetaNickname(value);
        return this;
    }

    @Override
    public MembersRecord value5(Boolean value) {
        setMetaIsOwner(value);
        return this;
    }

    @Override
    public MembersRecord value6(Boolean value) {
        setMetaIsAdministrator(value);
        return this;
    }

    @Override
    public MembersRecord value7(Long value) {
        setLevelPoints(value);
        return this;
    }

    @Override
    public MembersRecord values(Long value1, Long value2, LocalDateTime value3, String value4, Boolean value5, Boolean value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MembersRecord
     */
    public MembersRecord() {
        super(Members.MEMBERS);
    }

    /**
     * Create a detached, initialised MembersRecord
     */
    public MembersRecord(Long guildId, Long userId, LocalDateTime creationTimestamp, String metaNickname, Boolean metaIsOwner, Boolean metaIsAdministrator, Long levelPoints) {
        super(Members.MEMBERS);

        setGuildId(guildId);
        setUserId(userId);
        setCreationTimestamp(creationTimestamp);
        setMetaNickname(metaNickname);
        setMetaIsOwner(metaIsOwner);
        setMetaIsAdministrator(metaIsAdministrator);
        setLevelPoints(levelPoints);
    }
}
