/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.Channels;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelsRecord extends UpdatableRecordImpl<ChannelsRecord> implements Record6<Long, Long, LocalDateTime, Boolean, String, String> {

    private static final long serialVersionUID = -122138369;

    /**
     * Setter for <code>public.channels.channel_id</code>.
     */
    public ChannelsRecord setChannelId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.channels.channel_id</code>.
     */
    public Long getChannelId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.channels.guild_id</code>.
     */
    public ChannelsRecord setGuildId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.channels.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.channels.creation_timestamp</code>.
     */
    public ChannelsRecord setCreationTimestamp(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.channels.creation_timestamp</code>.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.channels.access_restriction</code>.
     */
    public ChannelsRecord setAccessRestriction(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.channels.access_restriction</code>.
     */
    public Boolean getAccessRestriction() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.channels.channel_type</code>.
     */
    public ChannelsRecord setChannelType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.channels.channel_type</code>.
     */
    public String getChannelType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.channels.channel_mode</code>.
     */
    public ChannelsRecord setChannelMode(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.channels.channel_mode</code>.
     */
    public String getChannelMode() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, LocalDateTime, Boolean, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, LocalDateTime, Boolean, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Channels.CHANNELS.CHANNEL_ID;
    }

    @Override
    public Field<Long> field2() {
        return Channels.CHANNELS.GUILD_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Channels.CHANNELS.CREATION_TIMESTAMP;
    }

    @Override
    public Field<Boolean> field4() {
        return Channels.CHANNELS.ACCESS_RESTRICTION;
    }

    @Override
    public Field<String> field5() {
        return Channels.CHANNELS.CHANNEL_TYPE;
    }

    @Override
    public Field<String> field6() {
        return Channels.CHANNELS.CHANNEL_MODE;
    }

    @Override
    public Long component1() {
        return getChannelId();
    }

    @Override
    public Long component2() {
        return getGuildId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationTimestamp();
    }

    @Override
    public Boolean component4() {
        return getAccessRestriction();
    }

    @Override
    public String component5() {
        return getChannelType();
    }

    @Override
    public String component6() {
        return getChannelMode();
    }

    @Override
    public Long value1() {
        return getChannelId();
    }

    @Override
    public Long value2() {
        return getGuildId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationTimestamp();
    }

    @Override
    public Boolean value4() {
        return getAccessRestriction();
    }

    @Override
    public String value5() {
        return getChannelType();
    }

    @Override
    public String value6() {
        return getChannelMode();
    }

    @Override
    public ChannelsRecord value1(Long value) {
        setChannelId(value);
        return this;
    }

    @Override
    public ChannelsRecord value2(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public ChannelsRecord value3(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public ChannelsRecord value4(Boolean value) {
        setAccessRestriction(value);
        return this;
    }

    @Override
    public ChannelsRecord value5(String value) {
        setChannelType(value);
        return this;
    }

    @Override
    public ChannelsRecord value6(String value) {
        setChannelMode(value);
        return this;
    }

    @Override
    public ChannelsRecord values(Long value1, Long value2, LocalDateTime value3, Boolean value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelsRecord
     */
    public ChannelsRecord() {
        super(Channels.CHANNELS);
    }

    /**
     * Create a detached, initialised ChannelsRecord
     */
    public ChannelsRecord(Long channelId, Long guildId, LocalDateTime creationTimestamp, Boolean accessRestriction, String channelType, String channelMode) {
        super(Channels.CHANNELS);

        set(0, channelId);
        set(1, guildId);
        set(2, creationTimestamp);
        set(3, accessRestriction);
        set(4, channelType);
        set(5, channelMode);
    }
}
