/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.Guilds;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record7<Long, LocalDateTime, String, Integer, Boolean, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.guilds.guild_id</code>.
     */
    public GuildsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guilds.creation_timestamp</code>.
     */
    public GuildsRecord setCreationTimestamp(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.creation_timestamp</code>.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.guilds.preferred_language</code>.
     */
    public GuildsRecord setPreferredLanguage(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.preferred_language</code>.
     */
    public String getPreferredLanguage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.guilds.license_id</code>.
     */
    public GuildsRecord setLicenseId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.license_id</code>.
     */
    public Integer getLicenseId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.guilds.use_vperms</code>.
     */
    public GuildsRecord setUseVperms(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.use_vperms</code>.
     */
    public Boolean getUseVperms() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.guilds.meta_guildname</code>.
     */
    public GuildsRecord setMetaGuildname(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.meta_guildname</code>.
     */
    public String getMetaGuildname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.guilds.meta_iconurl</code>.
     */
    public GuildsRecord setMetaIconurl(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.meta_iconurl</code>.
     */
    public String getMetaIconurl() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, LocalDateTime, String, Integer, Boolean, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, LocalDateTime, String, Integer, Boolean, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Guilds.GUILDS.GUILD_ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Guilds.GUILDS.CREATION_TIMESTAMP;
    }

    @Override
    public Field<String> field3() {
        return Guilds.GUILDS.PREFERRED_LANGUAGE;
    }

    @Override
    public Field<Integer> field4() {
        return Guilds.GUILDS.LICENSE_ID;
    }

    @Override
    public Field<Boolean> field5() {
        return Guilds.GUILDS.USE_VPERMS;
    }

    @Override
    public Field<String> field6() {
        return Guilds.GUILDS.META_GUILDNAME;
    }

    @Override
    public Field<String> field7() {
        return Guilds.GUILDS.META_ICONURL;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreationTimestamp();
    }

    @Override
    public String component3() {
        return getPreferredLanguage();
    }

    @Override
    public Integer component4() {
        return getLicenseId();
    }

    @Override
    public Boolean component5() {
        return getUseVperms();
    }

    @Override
    public String component6() {
        return getMetaGuildname();
    }

    @Override
    public String component7() {
        return getMetaIconurl();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreationTimestamp();
    }

    @Override
    public String value3() {
        return getPreferredLanguage();
    }

    @Override
    public Integer value4() {
        return getLicenseId();
    }

    @Override
    public Boolean value5() {
        return getUseVperms();
    }

    @Override
    public String value6() {
        return getMetaGuildname();
    }

    @Override
    public String value7() {
        return getMetaIconurl();
    }

    @Override
    public GuildsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildsRecord value2(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public GuildsRecord value3(String value) {
        setPreferredLanguage(value);
        return this;
    }

    @Override
    public GuildsRecord value4(Integer value) {
        setLicenseId(value);
        return this;
    }

    @Override
    public GuildsRecord value5(Boolean value) {
        setUseVperms(value);
        return this;
    }

    @Override
    public GuildsRecord value6(String value) {
        setMetaGuildname(value);
        return this;
    }

    @Override
    public GuildsRecord value7(String value) {
        setMetaIconurl(value);
        return this;
    }

    @Override
    public GuildsRecord values(Long value1, LocalDateTime value2, String value3, Integer value4, Boolean value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Long guildId, LocalDateTime creationTimestamp, String preferredLanguage, Integer licenseId, Boolean useVperms, String metaGuildname, String metaIconurl) {
        super(Guilds.GUILDS);

        setGuildId(guildId);
        setCreationTimestamp(creationTimestamp);
        setPreferredLanguage(preferredLanguage);
        setLicenseId(licenseId);
        setUseVperms(useVperms);
        setMetaGuildname(metaGuildname);
        setMetaIconurl(metaIconurl);
    }
}
