/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.Guilds;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record4<Long, LocalDateTime, String, Boolean> {

    private static final long serialVersionUID = -122588224;

    /**
     * Setter for <code>public.guilds.guild_id</code>.
     */
    public GuildsRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.guilds.creation_timestamp</code>.
     */
    public GuildsRecord setCreationTimestamp(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.creation_timestamp</code>.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.guilds.prefered_language</code>.
     */
    public GuildsRecord setPreferedLanguage(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.prefered_language</code>.
     */
    public String getPreferedLanguage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.guilds.use_extended_permissions</code>.
     */
    public GuildsRecord setUseExtendedPermissions(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.guilds.use_extended_permissions</code>.
     */
    public Boolean getUseExtendedPermissions() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, LocalDateTime, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, LocalDateTime, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Guilds.GUILDS.GUILD_ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Guilds.GUILDS.CREATION_TIMESTAMP;
    }

    @Override
    public Field<String> field3() {
        return Guilds.GUILDS.PREFERED_LANGUAGE;
    }

    @Override
    public Field<Boolean> field4() {
        return Guilds.GUILDS.USE_EXTENDED_PERMISSIONS;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreationTimestamp();
    }

    @Override
    public String component3() {
        return getPreferedLanguage();
    }

    @Override
    public Boolean component4() {
        return getUseExtendedPermissions();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreationTimestamp();
    }

    @Override
    public String value3() {
        return getPreferedLanguage();
    }

    @Override
    public Boolean value4() {
        return getUseExtendedPermissions();
    }

    @Override
    public GuildsRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public GuildsRecord value2(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public GuildsRecord value3(String value) {
        setPreferedLanguage(value);
        return this;
    }

    @Override
    public GuildsRecord value4(Boolean value) {
        setUseExtendedPermissions(value);
        return this;
    }

    @Override
    public GuildsRecord values(Long value1, LocalDateTime value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Long guildId, LocalDateTime creationTimestamp, String preferedLanguage, Boolean useExtendedPermissions) {
        super(Guilds.GUILDS);

        set(0, guildId);
        set(1, creationTimestamp);
        set(2, preferedLanguage);
        set(3, useExtendedPermissions);
    }
}
