/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.InternalBotShards;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalBotShardsRecord extends UpdatableRecordImpl<InternalBotShardsRecord> implements Record2<Integer, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.internal_bot_shards.shard_id</code>.
     */
    public InternalBotShardsRecord setShardId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.internal_bot_shards.shard_id</code>.
     */
    public Integer getShardId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.internal_bot_shards.client_id</code>.
     */
    public InternalBotShardsRecord setClientId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.internal_bot_shards.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return InternalBotShards.INTERNAL_BOT_SHARDS.SHARD_ID;
    }

    @Override
    public Field<Long> field2() {
        return InternalBotShards.INTERNAL_BOT_SHARDS.CLIENT_ID;
    }

    @Override
    public Integer component1() {
        return getShardId();
    }

    @Override
    public Long component2() {
        return getClientId();
    }

    @Override
    public Integer value1() {
        return getShardId();
    }

    @Override
    public Long value2() {
        return getClientId();
    }

    @Override
    public InternalBotShardsRecord value1(Integer value) {
        setShardId(value);
        return this;
    }

    @Override
    public InternalBotShardsRecord value2(Long value) {
        setClientId(value);
        return this;
    }

    @Override
    public InternalBotShardsRecord values(Integer value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InternalBotShardsRecord
     */
    public InternalBotShardsRecord() {
        super(InternalBotShards.INTERNAL_BOT_SHARDS);
    }

    /**
     * Create a detached, initialised InternalBotShardsRecord
     */
    public InternalBotShardsRecord(Integer shardId, Long clientId) {
        super(InternalBotShards.INTERNAL_BOT_SHARDS);

        setShardId(shardId);
        setClientId(clientId);
    }
}
