/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.Members;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembersRecord extends UpdatableRecordImpl<MembersRecord> implements Record4<Long, Long, LocalDateTime, Long> {

    private static final long serialVersionUID = -946608374;

    /**
     * Setter for <code>public.members.guild_id</code>.
     */
    public MembersRecord setGuildId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.members.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.members.user_id</code>.
     */
    public MembersRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.members.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.members.creation_timestamp</code>.
     */
    public MembersRecord setCreationTimestamp(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.members.creation_timestamp</code>.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.members.gained_xp</code>.
     */
    public MembersRecord setGainedXp(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.members.gained_xp</code>.
     */
    public Long getGainedXp() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, LocalDateTime, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, LocalDateTime, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Members.MEMBERS.GUILD_ID;
    }

    @Override
    public Field<Long> field2() {
        return Members.MEMBERS.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Members.MEMBERS.CREATION_TIMESTAMP;
    }

    @Override
    public Field<Long> field4() {
        return Members.MEMBERS.GAINED_XP;
    }

    @Override
    public Long component1() {
        return getGuildId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationTimestamp();
    }

    @Override
    public Long component4() {
        return getGainedXp();
    }

    @Override
    public Long value1() {
        return getGuildId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationTimestamp();
    }

    @Override
    public Long value4() {
        return getGainedXp();
    }

    @Override
    public MembersRecord value1(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public MembersRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public MembersRecord value3(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public MembersRecord value4(Long value) {
        setGainedXp(value);
        return this;
    }

    @Override
    public MembersRecord values(Long value1, Long value2, LocalDateTime value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MembersRecord
     */
    public MembersRecord() {
        super(Members.MEMBERS);
    }

    /**
     * Create a detached, initialised MembersRecord
     */
    public MembersRecord(Long guildId, Long userId, LocalDateTime creationTimestamp, Long gainedXp) {
        super(Members.MEMBERS);

        set(0, guildId);
        set(1, userId);
        set(2, creationTimestamp);
        set(3, gainedXp);
    }
}
