/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.PollsOptions;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PollsOptionsRecord extends UpdatableRecordImpl<PollsOptionsRecord> implements Record3<Long, Integer, String> {

    private static final long serialVersionUID = -815116682;

    /**
     * Setter for <code>public.polls_options.poll_id</code>.
     */
    public PollsOptionsRecord setPollId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.polls_options.poll_id</code>.
     */
    public Long getPollId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.polls_options.poll_option_id</code>.
     */
    public PollsOptionsRecord setPollOptionId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.polls_options.poll_option_id</code>.
     */
    public Integer getPollOptionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.polls_options.poll_option_description</code>.
     */
    public PollsOptionsRecord setPollOptionDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.polls_options.poll_option_description</code>.
     */
    public String getPollOptionDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PollsOptions.POLLS_OPTIONS.POLL_ID;
    }

    @Override
    public Field<Integer> field2() {
        return PollsOptions.POLLS_OPTIONS.POLL_OPTION_ID;
    }

    @Override
    public Field<String> field3() {
        return PollsOptions.POLLS_OPTIONS.POLL_OPTION_DESCRIPTION;
    }

    @Override
    public Long component1() {
        return getPollId();
    }

    @Override
    public Integer component2() {
        return getPollOptionId();
    }

    @Override
    public String component3() {
        return getPollOptionDescription();
    }

    @Override
    public Long value1() {
        return getPollId();
    }

    @Override
    public Integer value2() {
        return getPollOptionId();
    }

    @Override
    public String value3() {
        return getPollOptionDescription();
    }

    @Override
    public PollsOptionsRecord value1(Long value) {
        setPollId(value);
        return this;
    }

    @Override
    public PollsOptionsRecord value2(Integer value) {
        setPollOptionId(value);
        return this;
    }

    @Override
    public PollsOptionsRecord value3(String value) {
        setPollOptionDescription(value);
        return this;
    }

    @Override
    public PollsOptionsRecord values(Long value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PollsOptionsRecord
     */
    public PollsOptionsRecord() {
        super(PollsOptions.POLLS_OPTIONS);
    }

    /**
     * Create a detached, initialised PollsOptionsRecord
     */
    public PollsOptionsRecord(Long pollId, Integer pollOptionId, String pollOptionDescription) {
        super(PollsOptions.POLLS_OPTIONS);

        set(0, pollId);
        set(1, pollOptionId);
        set(2, pollOptionDescription);
    }
}
