/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.RolesUser;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesUserRecord extends UpdatableRecordImpl<RolesUserRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -255966931;

    /**
     * Setter for <code>public.roles_user.role_id</code>.
     */
    public RolesUserRecord setRoleId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.roles_user.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.roles_user.user_id</code>.
     */
    public RolesUserRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.roles_user.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RolesUser.ROLES_USER.ROLE_ID;
    }

    @Override
    public Field<Long> field2() {
        return RolesUser.ROLES_USER.USER_ID;
    }

    @Override
    public Long component1() {
        return getRoleId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getRoleId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public RolesUserRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolesUserRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public RolesUserRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesUserRecord
     */
    public RolesUserRecord() {
        super(RolesUser.ROLES_USER);
    }

    /**
     * Create a detached, initialised RolesUserRecord
     */
    public RolesUserRecord(Long roleId, Long userId) {
        super(RolesUser.ROLES_USER);

        set(0, roleId);
        set(1, userId);
    }
}
