/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.Roles;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> implements Record4<Long, Long, LocalDateTime, String> {

    private static final long serialVersionUID = -5179795;

    /**
     * Setter for <code>public.roles.role_id</code>.
     */
    public RolesRecord setRoleId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.roles.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.roles.guild_id</code>.
     */
    public RolesRecord setGuildId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.roles.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.roles.creation_timestamp</code>.
     */
    public RolesRecord setCreationTimestamp(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.roles.creation_timestamp</code>.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.roles.role_name</code>.
     */
    public RolesRecord setRoleName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.roles.role_name</code>.
     */
    public String getRoleName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, LocalDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, LocalDateTime, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Roles.ROLES.ROLE_ID;
    }

    @Override
    public Field<Long> field2() {
        return Roles.ROLES.GUILD_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Roles.ROLES.CREATION_TIMESTAMP;
    }

    @Override
    public Field<String> field4() {
        return Roles.ROLES.ROLE_NAME;
    }

    @Override
    public Long component1() {
        return getRoleId();
    }

    @Override
    public Long component2() {
        return getGuildId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreationTimestamp();
    }

    @Override
    public String component4() {
        return getRoleName();
    }

    @Override
    public Long value1() {
        return getRoleId();
    }

    @Override
    public Long value2() {
        return getGuildId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreationTimestamp();
    }

    @Override
    public String value4() {
        return getRoleName();
    }

    @Override
    public RolesRecord value1(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RolesRecord value2(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public RolesRecord value3(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public RolesRecord value4(String value) {
        setRoleName(value);
        return this;
    }

    @Override
    public RolesRecord values(Long value1, Long value2, LocalDateTime value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesRecord
     */
    public RolesRecord() {
        super(Roles.ROLES);
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(Long roleId, Long guildId, LocalDateTime creationTimestamp, String roleName) {
        super(Roles.ROLES);

        set(0, roleId);
        set(1, guildId);
        set(2, creationTimestamp);
        set(3, roleName);
    }
}
