/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables.records;


import de.netbeacon.xenia.joop.tables.UsersOauthScopes;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersOauthScopesRecord extends UpdatableRecordImpl<UsersOauthScopesRecord> implements Record20<Long, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> {

    private static final long serialVersionUID = 1881150697;

    /**
     * Setter for <code>public.users_oauth_scopes.entry_id</code>.
     */
    public UsersOauthScopesRecord setEntryId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.entry_id</code>.
     */
    public Long getEntryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_bot</code>.
     */
    public UsersOauthScopesRecord setScopeBot(Boolean value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_bot</code>.
     */
    public Boolean getScopeBot() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_connections</code>.
     */
    public UsersOauthScopesRecord setScopeConnections(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_connections</code>.
     */
    public Boolean getScopeConnections() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_email</code>.
     */
    public UsersOauthScopesRecord setScopeEmail(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_email</code>.
     */
    public Boolean getScopeEmail() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_identify</code>.
     */
    public UsersOauthScopesRecord setScopeIdentify(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_identify</code>.
     */
    public Boolean getScopeIdentify() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_guilds</code>.
     */
    public UsersOauthScopesRecord setScopeGuilds(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_guilds</code>.
     */
    public Boolean getScopeGuilds() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_guilds_join</code>.
     */
    public UsersOauthScopesRecord setScopeGuildsJoin(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_guilds_join</code>.
     */
    public Boolean getScopeGuildsJoin() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_gdm_join</code>.
     */
    public UsersOauthScopesRecord setScopeGdmJoin(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_gdm_join</code>.
     */
    public Boolean getScopeGdmJoin() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_messages_read</code>.
     */
    public UsersOauthScopesRecord setScopeMessagesRead(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_messages_read</code>.
     */
    public Boolean getScopeMessagesRead() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_rpc</code>.
     */
    public UsersOauthScopesRecord setScopeRpc(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_rpc</code>.
     */
    public Boolean getScopeRpc() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_rpc_api</code>.
     */
    public UsersOauthScopesRecord setScopeRpcApi(Boolean value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_rpc_api</code>.
     */
    public Boolean getScopeRpcApi() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_rpc_notifications_read</code>.
     */
    public UsersOauthScopesRecord setScopeRpcNotificationsRead(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_rpc_notifications_read</code>.
     */
    public Boolean getScopeRpcNotificationsRead() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_webhook_incoming</code>.
     */
    public UsersOauthScopesRecord setScopeWebhookIncoming(Boolean value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_webhook_incoming</code>.
     */
    public Boolean getScopeWebhookIncoming() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_applications_builds_upload</code>.
     */
    public UsersOauthScopesRecord setScopeApplicationsBuildsUpload(Boolean value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_applications_builds_upload</code>.
     */
    public Boolean getScopeApplicationsBuildsUpload() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_applications_builds_read</code>.
     */
    public UsersOauthScopesRecord setScopeApplicationsBuildsRead(Boolean value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_applications_builds_read</code>.
     */
    public Boolean getScopeApplicationsBuildsRead() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_applications_store_update</code>.
     */
    public UsersOauthScopesRecord setScopeApplicationsStoreUpdate(Boolean value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_applications_store_update</code>.
     */
    public Boolean getScopeApplicationsStoreUpdate() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_applications_entitlements</code>.
     */
    public UsersOauthScopesRecord setScopeApplicationsEntitlements(Boolean value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_applications_entitlements</code>.
     */
    public Boolean getScopeApplicationsEntitlements() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_relationships_read</code>.
     */
    public UsersOauthScopesRecord setScopeRelationshipsRead(Boolean value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_relationships_read</code>.
     */
    public Boolean getScopeRelationshipsRead() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_activities_read</code>.
     */
    public UsersOauthScopesRecord setScopeActivitiesRead(Boolean value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_activities_read</code>.
     */
    public Boolean getScopeActivitiesRead() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>public.users_oauth_scopes.scope_activities_write</code>.
     */
    public UsersOauthScopesRecord setScopeActivitiesWrite(Boolean value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.users_oauth_scopes.scope_activities_write</code>.
     */
    public Boolean getScopeActivitiesWrite() {
        return (Boolean) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row20<Long, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    @Override
    public Row20<Long, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean> valuesRow() {
        return (Row20) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.ENTRY_ID;
    }

    @Override
    public Field<Boolean> field2() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_BOT;
    }

    @Override
    public Field<Boolean> field3() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_CONNECTIONS;
    }

    @Override
    public Field<Boolean> field4() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_EMAIL;
    }

    @Override
    public Field<Boolean> field5() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_IDENTIFY;
    }

    @Override
    public Field<Boolean> field6() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_GUILDS;
    }

    @Override
    public Field<Boolean> field7() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_GUILDS_JOIN;
    }

    @Override
    public Field<Boolean> field8() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_GDM_JOIN;
    }

    @Override
    public Field<Boolean> field9() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_MESSAGES_READ;
    }

    @Override
    public Field<Boolean> field10() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_RPC;
    }

    @Override
    public Field<Boolean> field11() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_RPC_API;
    }

    @Override
    public Field<Boolean> field12() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_RPC_NOTIFICATIONS_READ;
    }

    @Override
    public Field<Boolean> field13() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_WEBHOOK_INCOMING;
    }

    @Override
    public Field<Boolean> field14() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_APPLICATIONS_BUILDS_UPLOAD;
    }

    @Override
    public Field<Boolean> field15() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_APPLICATIONS_BUILDS_READ;
    }

    @Override
    public Field<Boolean> field16() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_APPLICATIONS_STORE_UPDATE;
    }

    @Override
    public Field<Boolean> field17() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_APPLICATIONS_ENTITLEMENTS;
    }

    @Override
    public Field<Boolean> field18() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_RELATIONSHIPS_READ;
    }

    @Override
    public Field<Boolean> field19() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_ACTIVITIES_READ;
    }

    @Override
    public Field<Boolean> field20() {
        return UsersOauthScopes.USERS_OAUTH_SCOPES.SCOPE_ACTIVITIES_WRITE;
    }

    @Override
    public Long component1() {
        return getEntryId();
    }

    @Override
    public Boolean component2() {
        return getScopeBot();
    }

    @Override
    public Boolean component3() {
        return getScopeConnections();
    }

    @Override
    public Boolean component4() {
        return getScopeEmail();
    }

    @Override
    public Boolean component5() {
        return getScopeIdentify();
    }

    @Override
    public Boolean component6() {
        return getScopeGuilds();
    }

    @Override
    public Boolean component7() {
        return getScopeGuildsJoin();
    }

    @Override
    public Boolean component8() {
        return getScopeGdmJoin();
    }

    @Override
    public Boolean component9() {
        return getScopeMessagesRead();
    }

    @Override
    public Boolean component10() {
        return getScopeRpc();
    }

    @Override
    public Boolean component11() {
        return getScopeRpcApi();
    }

    @Override
    public Boolean component12() {
        return getScopeRpcNotificationsRead();
    }

    @Override
    public Boolean component13() {
        return getScopeWebhookIncoming();
    }

    @Override
    public Boolean component14() {
        return getScopeApplicationsBuildsUpload();
    }

    @Override
    public Boolean component15() {
        return getScopeApplicationsBuildsRead();
    }

    @Override
    public Boolean component16() {
        return getScopeApplicationsStoreUpdate();
    }

    @Override
    public Boolean component17() {
        return getScopeApplicationsEntitlements();
    }

    @Override
    public Boolean component18() {
        return getScopeRelationshipsRead();
    }

    @Override
    public Boolean component19() {
        return getScopeActivitiesRead();
    }

    @Override
    public Boolean component20() {
        return getScopeActivitiesWrite();
    }

    @Override
    public Long value1() {
        return getEntryId();
    }

    @Override
    public Boolean value2() {
        return getScopeBot();
    }

    @Override
    public Boolean value3() {
        return getScopeConnections();
    }

    @Override
    public Boolean value4() {
        return getScopeEmail();
    }

    @Override
    public Boolean value5() {
        return getScopeIdentify();
    }

    @Override
    public Boolean value6() {
        return getScopeGuilds();
    }

    @Override
    public Boolean value7() {
        return getScopeGuildsJoin();
    }

    @Override
    public Boolean value8() {
        return getScopeGdmJoin();
    }

    @Override
    public Boolean value9() {
        return getScopeMessagesRead();
    }

    @Override
    public Boolean value10() {
        return getScopeRpc();
    }

    @Override
    public Boolean value11() {
        return getScopeRpcApi();
    }

    @Override
    public Boolean value12() {
        return getScopeRpcNotificationsRead();
    }

    @Override
    public Boolean value13() {
        return getScopeWebhookIncoming();
    }

    @Override
    public Boolean value14() {
        return getScopeApplicationsBuildsUpload();
    }

    @Override
    public Boolean value15() {
        return getScopeApplicationsBuildsRead();
    }

    @Override
    public Boolean value16() {
        return getScopeApplicationsStoreUpdate();
    }

    @Override
    public Boolean value17() {
        return getScopeApplicationsEntitlements();
    }

    @Override
    public Boolean value18() {
        return getScopeRelationshipsRead();
    }

    @Override
    public Boolean value19() {
        return getScopeActivitiesRead();
    }

    @Override
    public Boolean value20() {
        return getScopeActivitiesWrite();
    }

    @Override
    public UsersOauthScopesRecord value1(Long value) {
        setEntryId(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value2(Boolean value) {
        setScopeBot(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value3(Boolean value) {
        setScopeConnections(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value4(Boolean value) {
        setScopeEmail(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value5(Boolean value) {
        setScopeIdentify(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value6(Boolean value) {
        setScopeGuilds(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value7(Boolean value) {
        setScopeGuildsJoin(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value8(Boolean value) {
        setScopeGdmJoin(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value9(Boolean value) {
        setScopeMessagesRead(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value10(Boolean value) {
        setScopeRpc(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value11(Boolean value) {
        setScopeRpcApi(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value12(Boolean value) {
        setScopeRpcNotificationsRead(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value13(Boolean value) {
        setScopeWebhookIncoming(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value14(Boolean value) {
        setScopeApplicationsBuildsUpload(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value15(Boolean value) {
        setScopeApplicationsBuildsRead(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value16(Boolean value) {
        setScopeApplicationsStoreUpdate(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value17(Boolean value) {
        setScopeApplicationsEntitlements(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value18(Boolean value) {
        setScopeRelationshipsRead(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value19(Boolean value) {
        setScopeActivitiesRead(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord value20(Boolean value) {
        setScopeActivitiesWrite(value);
        return this;
    }

    @Override
    public UsersOauthScopesRecord values(Long value1, Boolean value2, Boolean value3, Boolean value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8, Boolean value9, Boolean value10, Boolean value11, Boolean value12, Boolean value13, Boolean value14, Boolean value15, Boolean value16, Boolean value17, Boolean value18, Boolean value19, Boolean value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersOauthScopesRecord
     */
    public UsersOauthScopesRecord() {
        super(UsersOauthScopes.USERS_OAUTH_SCOPES);
    }

    /**
     * Create a detached, initialised UsersOauthScopesRecord
     */
    public UsersOauthScopesRecord(Long entryId, Boolean scopeBot, Boolean scopeConnections, Boolean scopeEmail, Boolean scopeIdentify, Boolean scopeGuilds, Boolean scopeGuildsJoin, Boolean scopeGdmJoin, Boolean scopeMessagesRead, Boolean scopeRpc, Boolean scopeRpcApi, Boolean scopeRpcNotificationsRead, Boolean scopeWebhookIncoming, Boolean scopeApplicationsBuildsUpload, Boolean scopeApplicationsBuildsRead, Boolean scopeApplicationsStoreUpdate, Boolean scopeApplicationsEntitlements, Boolean scopeRelationshipsRead, Boolean scopeActivitiesRead, Boolean scopeActivitiesWrite) {
        super(UsersOauthScopes.USERS_OAUTH_SCOPES);

        set(0, entryId);
        set(1, scopeBot);
        set(2, scopeConnections);
        set(3, scopeEmail);
        set(4, scopeIdentify);
        set(5, scopeGuilds);
        set(6, scopeGuildsJoin);
        set(7, scopeGdmJoin);
        set(8, scopeMessagesRead);
        set(9, scopeRpc);
        set(10, scopeRpcApi);
        set(11, scopeRpcNotificationsRead);
        set(12, scopeWebhookIncoming);
        set(13, scopeApplicationsBuildsUpload);
        set(14, scopeApplicationsBuildsRead);
        set(15, scopeApplicationsStoreUpdate);
        set(16, scopeApplicationsEntitlements);
        set(17, scopeRelationshipsRead);
        set(18, scopeActivitiesRead);
        set(19, scopeActivitiesWrite);
    }
}
