/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop.tables;


import de.netbeacon.xenia.joop.Keys;
import de.netbeacon.xenia.joop.Public;
import de.netbeacon.xenia.joop.tables.records.VrolesRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vroles extends TableImpl<VrolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vroles</code>
     */
    public static final Vroles VROLES = new Vroles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VrolesRecord> getRecordType() {
        return VrolesRecord.class;
    }

    /**
     * The column <code>public.vroles.vrole_id</code>.
     */
    public final TableField<VrolesRecord, Long> VROLE_ID = createField(DSL.name("vrole_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.vroles.guild_id</code>.
     */
    public final TableField<VrolesRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vroles.creation_timestamp</code>.
     */
    public final TableField<VrolesRecord, LocalDateTime> CREATION_TIMESTAMP = createField(DSL.name("creation_timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.vroles.vrole_name</code>.
     */
    public final TableField<VrolesRecord, String> VROLE_NAME = createField(DSL.name("vrole_name"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field("'unnamed_role'::character varying", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.vroles.vrole_permission</code>.
     */
    public final TableField<VrolesRecord, Long> VROLE_PERMISSION = createField(DSL.name("vrole_permission"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("'0'::bigint", SQLDataType.BIGINT)), this, "");

    private Vroles(Name alias, Table<VrolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Vroles(Name alias, Table<VrolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.vroles</code> table reference
     */
    public Vroles(String alias) {
        this(DSL.name(alias), VROLES);
    }

    /**
     * Create an aliased <code>public.vroles</code> table reference
     */
    public Vroles(Name alias) {
        this(alias, VROLES);
    }

    /**
     * Create a <code>public.vroles</code> table reference
     */
    public Vroles() {
        this(DSL.name("vroles"), null);
    }

    public <O extends Record> Vroles(Table<O> child, ForeignKey<O, VrolesRecord> key) {
        super(child, key, VROLES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<VrolesRecord, Long> getIdentity() {
        return (Identity<VrolesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VrolesRecord> getPrimaryKey() {
        return Keys.ROLES_ROLE_ID;
    }

    @Override
    public List<UniqueKey<VrolesRecord>> getKeys() {
        return Arrays.<UniqueKey<VrolesRecord>>asList(Keys.ROLES_ROLE_ID, Keys.ROLES_GUILD_ID_ROLE_NAME);
    }

    @Override
    public Vroles as(String alias) {
        return new Vroles(DSL.name(alias), this);
    }

    @Override
    public Vroles as(Name alias) {
        return new Vroles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Vroles rename(String name) {
        return new Vroles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Vroles rename(Name name) {
        return new Vroles(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, LocalDateTime, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
