/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop;


import de.netbeacon.xenia.joop.tables.Channels;
import de.netbeacon.xenia.joop.tables.Guilds;
import de.netbeacon.xenia.joop.tables.Members;
import de.netbeacon.xenia.joop.tables.MembersRoles;
import de.netbeacon.xenia.joop.tables.Permission;
import de.netbeacon.xenia.joop.tables.Roles;
import de.netbeacon.xenia.joop.tables.RolesPermission;
import de.netbeacon.xenia.joop.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -747460699;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.channels</code>.
     */
    public final Channels CHANNELS = Channels.CHANNELS;

    /**
     * The table <code>public.guilds</code>.
     */
    public final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.members</code>.
     */
    public final Members MEMBERS = Members.MEMBERS;

    /**
     * The table <code>public.members_roles</code>.
     */
    public final MembersRoles MEMBERS_ROLES = MembersRoles.MEMBERS_ROLES;

    /**
     * The table <code>public.permission</code>.
     */
    public final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.roles_permission</code>.
     */
    public final RolesPermission ROLES_PERMISSION = RolesPermission.ROLES_PERMISSION;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.PERMISSION_PERMISSION_ID_SEQ,
            Sequences.ROLES_ROLE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Channels.CHANNELS,
            Guilds.GUILDS,
            Members.MEMBERS,
            MembersRoles.MEMBERS_ROLES,
            Permission.PERMISSION,
            Roles.ROLES,
            RolesPermission.ROLES_PERMISSION,
            Users.USERS);
    }
}
