/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.licenses_license_id_seq</code>
     */
    public static final Sequence<Integer> LICENSES_LICENSE_ID_SEQ = Internal.createSequence("licenses_license_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.permission_permission_id_seq</code>
     */
    public static final Sequence<Integer> PERMISSION_PERMISSION_ID_SEQ = Internal.createSequence("permission_permission_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.roles_role_id_seq</code>
     */
    public static final Sequence<Integer> ROLES_ROLE_ID_SEQ = Internal.createSequence("roles_role_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
