/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.joop;


import de.netbeacon.xenia.joop.tables.*;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.channels</code>.
     */
    public static final Channels CHANNELS = Channels.CHANNELS;

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.internal_bot_data</code>.
     */
    public static final InternalBotData INTERNAL_BOT_DATA = InternalBotData.INTERNAL_BOT_DATA;

    /**
     * The table <code>public.internal_bot_shards</code>.
     */
    public static final InternalBotShards INTERNAL_BOT_SHARDS = InternalBotShards.INTERNAL_BOT_SHARDS;

    /**
     * The table <code>public.license_types</code>.
     */
    public static final LicenseTypes LICENSE_TYPES = LicenseTypes.LICENSE_TYPES;

    /**
     * The table <code>public.licenses</code>.
     */
    public static final Licenses LICENSES = Licenses.LICENSES;

    /**
     * The table <code>public.members</code>.
     */
    public static final Members MEMBERS = Members.MEMBERS;

    /**
     * The table <code>public.members_roles</code>.
     */
    public static final MembersRoles MEMBERS_ROLES = MembersRoles.MEMBERS_ROLES;

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.permission</code>.
     */
    public static final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.roles_permission</code>.
     */
    public static final RolesPermission ROLES_PERMISSION = RolesPermission.ROLES_PERMISSION;

    /**
     * The table <code>public.tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.users_oauth</code>.
     */
    public static final UsersOauth USERS_OAUTH = UsersOauth.USERS_OAUTH;

    /**
     * The table <code>public.users_oauth_scopes</code>.
     */
    public static final UsersOauthScopes USERS_OAUTH_SCOPES = UsersOauthScopes.USERS_OAUTH_SCOPES;
}
