/*
 * This file is generated by jOOQ.
 */
package de.netbeacon.xenia.jooq;


import de.netbeacon.xenia.jooq.tables.*;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.channels</code>.
     */
    public static final Channels CHANNELS = Channels.CHANNELS;

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.internal_bot_data</code>.
     */
    public static final InternalBotData INTERNAL_BOT_DATA = InternalBotData.INTERNAL_BOT_DATA;

    /**
     * The table <code>public.internal_bot_shards</code>.
     */
    public static final InternalBotShards INTERNAL_BOT_SHARDS = InternalBotShards.INTERNAL_BOT_SHARDS;

    /**
     * The table <code>public.license_types</code>.
     */
    public static final LicenseTypes LICENSE_TYPES = LicenseTypes.LICENSE_TYPES;

    /**
     * The table <code>public.licenses</code>.
     */
    public static final Licenses LICENSES = Licenses.LICENSES;

    /**
     * The table <code>public.members</code>.
     */
    public static final Members MEMBERS = Members.MEMBERS;

    /**
     * The table <code>public.members_roles</code>.
     */
    public static final MembersRoles MEMBERS_ROLES = MembersRoles.MEMBERS_ROLES;

    /**
     * The table <code>public.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>public.notification</code>.
     */
    public static final Notification NOTIFICATION = Notification.NOTIFICATION;

    /**
     * The table <code>public.oauth</code>.
     */
    public static final Oauth OAUTH = Oauth.OAUTH;

    /**
     * The table <code>public.oauth_states</code>.
     */
    public static final OauthStates OAUTH_STATES = OauthStates.OAUTH_STATES;

    /**
     * The table <code>public.tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.twitchnotifications</code>.
     */
    public static final Twitchnotifications TWITCHNOTIFICATIONS = Twitchnotifications.TWITCHNOTIFICATIONS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.vroles</code>.
     */
    public static final Vroles VROLES = Vroles.VROLES;
}
